### ISSUE TITLE
GDBM is under GPL.  This library must also be.

### ISSUE THREAD

**Issue by shyouhei** [ruby/gdbm#8]
GDBM is under GPL, not under LGPL.  Programs that link to GDBM _must_ also be GPL.

This was not a problem before, because this library was a part of ruby/ruby.

- Ruby works well without gdbm.  There were no need to make it always GPLed.
- At the beginning ruby was dual-licensed to GPL and Ruby's.  Users of GDBM could choose GPL.

However now that it is split into a separate library.   It is very hard for this library to exist without GDBM.  It seems GPL pollution is inevitable now.

**Comment by ioquatix** [comment]
Does anyone use this code? Can we deprecate it and remove it in Ruby 3?

**Comment by shyouhei** [comment]
No need to deprecate.  This library could live as a normal gem.  Just removing it from the ruby distribution -- like we already did for rake etc. -- should just suffice, I think.

**Comment by ioquatix** [comment]
That's what I suggested, not including it in the core distribution - it can just be a gem.

**Comment by ioquatix** [comment]
Maybe update the license on the README and add a warning?

**Comment by hsbt** [comment]
@shyouhei I will change the current license to GPL. But I'm not sure what we chose GPL version?

**Comment by shyouhei** [comment]
GPL version 2 says:

> This program is free software; you can redistribute it and/or
> modify it under the terms of the GNU General Public License
> as published by the Free Software Foundation; either version 2
> of the License, or (at your option) any later version.

The "any later version" clause covers version 3.  I guess it's the safest for this library to choose GPL version 2.

**Comment by micwoj92** [comment]
Is it possible to release new version of this gem to have version with proper license on https://rubygems.org/gems/gdbm? Thanks

**Comment by hsbt** [comment]
@micwoj92 https://rubygems.org/gems/gdbm/versions/2.1.1
